services:
  - type: web
    name: customer-segmentation-backend
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app

    pythonVersion: "3.11.9"
